### ISSUE TITLE
Wrong default mapping

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#1223]
When I import this file [011.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/6885049/011.xlsx), 
`Study Id` and `Subject Id` are interpreted as Measurement and Error in the defualt mapping.
![grafik](https://user-images.githubusercontent.com/25061876/127147374-3512ca3c-f855-4b34-aad8-f62a3fe89707.png)

And when I import this file [011_2.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/6885065/011_2.xlsx) (just changed the order of columns) - Measurement is properyl mapped per default, but Error is mapped to the Study Id 
(interestingly also assuming arithmetic error with the same unit as measurement).
![grafik](https://user-images.githubusercontent.com/25061876/127147688-1ea6b623-e093-46c7-ab20-63e831eb4554.png)

**Comment by abdelr** [comment]
@Yuri05 the automatic recognition of columns occurs as follows:

1. For each element at columnInfos a column starting with the same name is searched in a non case sensitive way. This means that for "Measurement" for example, columns with the name "measurement1" or "MEASUREMENT" will be a match but not "Concentration".
2. After the search based on the name is finished, columns are still tried to match to existing unused excel columns checking just the data type. This is why "Study Id" (numeric values) and "Subject Id" are used as Measurement and Error.

Solving this should be easy in the sense that we just need to change the order in which the functions are invoked. I would rather discuss it a bit first since for example, we say that a file is valid if it has two numeric columns at least (time, measurement). This is why assigning these columns is the priority. But then, if we say we have "Time" and "Study Id" so the file is valid, why should the initial mapping take "Study Id" as a metadata instead of the actual measurement ending in an invalid initial state. I do see your point with these files though. At the end this is just a preset of the mapping that the user could still change so it is not really critical to make it perfect. I am willing to do some changes here but let us just think together if you like about all possible situations before changing something just before the release.
