### ISSUE TITLE
Include PK Properties for Population Simulations

### ISSUE THREAD

**Issue by abdelr** [Open-Systems-Pharmacology/OSPSuite.Core#1406]

**Comment by PavelBal** [comment]
## Problem


For population simulations, not all of the PK parameters are calculated. Furthermore, the values are not calculated for the selected ranges (e.g., 5%-95%).
Following PK-parameters should be calculated for the selected outputs and are displayed but not calculated (values are NaN, see Figure 1):
•	AUC_inf_norm
•	AUC_tEnd_norm
•	C_max_norm
•	Total body clearance/F (not quite clear what it is, documentation missing)
•	Vd(plasma)/F
•	Vss(plasma)/F

![image](https://user-images.githubusercontent.com/25903040/146915786-08a10283-0d4e-4a36-8de3-5e3fd42e6dc8.png)
Figure 1

Following parameters are calculated in individual simulation for all compounds and are not calculated for population simulations:
•	AUC Ratio (for DDI simulations only)
•	C_max Ratio (for DDI simulations only)
•	Total plasma clearance
•	Vd (plasma)
•	Vss(phys-chem) (iv simulations)
•	VSS(plasma)
•	Bioavailability (oral simulations)
•	Fraction absorbed (oral simulations)

## Proposed solution

1)	Present PK-parameter values for the selected ranges. PK-parameters for the selected outputs should be presented for all selected outputs, including ranges. In particular, these are:
•	Arithmetic Standard Deviation – present as 1234
•	Geometric Standard Deviation - present as 1234
•	Range 5% to 95% - show two columns for 5% and 95% percentiles
•	Range 2.5% to 97.5% - show two columns for 2.5% and 97.5% percentiles

2)	Investigate why some PK-Parameters are calculated as “NaN” and fix if possible
3)	Enable calculation of missing PK-Parameters. For parameters that require additional simulation runs (AUC_ratio, C_max_ratio, bioavailability), show a warning message to the user that this will require calculation of the whole population and might take much time.
It remains to clarify for which outputs these parameters should be calculated. Arithmetic mean in venous blood plasma?

**Comment by msevestre** [comment]
I am not quite sure that the implementation belongs in core at the moment. I will investigate the code and get back to you.
Also I will explain why some parameters are NaN. This is on purpose

**Comment by msevestre** [comment]
_norm are `normalized to dose, with dose in drug mass per body weight`. That does not make sense to display them for a curve based on mean or percentile etc... There is no "BW" that we can use. Maybe we could do something special when the application unit is mg/kg but this was not deemed necessary at the time

>Arithmetic Standard Deviation – present as 1234

I don't understand what you mean with 1234

>It remains to clarify for which outputs these parameters should be calculated. Arithmetic mean in venous blood plasma?

I depends on the species (Peripheral venous blood except for mouse and rat where it is venous blood)

**Comment by msevestre** [comment]
• Total body clearance/F
• Vd(plasma)/F
• Vss(plasma)/F

They are NaN for the same reason. Total body clearance is calculated using the Total Drug mass per body weight. Since we are using mean, percentile, max etc... there is no dose per body weight that can be calculated. So we set it to NaN. Vd and vss are using CL so they are NaN also

**Comment by msevestre** [comment]
>Enable calculation of missing PK-Parameters. For parameters that require additional simulation runs (AUC_ratio, C_max_ratio, bioavailability), show a warning message to the user that this will require calculation of the whole population and might take much time.

We would have to document that we are using the mean somehow... Does it really make sense to calculate those values using the mean? Bioavailaibility, AUC might differ significantly between individual of a populations...

**Comment by msevestre** [comment]
oh with 1234 you mean probably the value? :)

**Comment by PavelBal** [comment]
> _norm are normalized to dose, with dose in drug mass per body weight. That does not make sense to display them for a curve based on mean or percentile etc... There is no "BW" that we can use.

Yes, I understand the problem here. I think we at least should add a tooltip explaining why the values are not calculated? Or just do not show these rows at all?

In general, the PK-parameters there are calculated for the curves... Would it actually not make more sense to show the values for the aggregation of single PK-parameter values? E.g., for selected "mean AUC", show the mean of individual AUC values (which are calculated already), for percentiles the same etc... At least for me it sounds like the more _correct_ thing to show. Then we could also show the normalized values as we have the BW for the single individuals...

> I don't understand what you mean with 1234

Yepp, just a single numerical value..

> We would have to document that we are using the mean somehow... Does it really make sense to calculate those values using the mean? Bioavailaibility, AUC might differ significantly between individual of a populations...

I would add it to the tooltip (the same way the tooltip for individual simulations states that the PSV concentration is used..). And also here I would calculate the mean of the individual PK-parameter values, not based on the mean curve. Additionally, these parameters (AUC_ratio/C_max_ratio/bioavailability) can then be shown as box whisker/scatter/range, which are definitely very useful outputs.

**Comment by Yuri05** [comment]
implemented in 11.1
