### ISSUE TITLE
Importer allows for too many dimensions when setting the unit of measurement

### ISSUE THREAD

**Issue by abdelr** [Open-Systems-Pharmacology/OSPSuite.Core#1426]
**Steps to reproduce:**
1. Open importer
2. Select file [BookPercent.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/7824394/BookPercent.xlsx)
3. Click on the Edit Extra Fields cell on Measurement
4. Click on Dimension
 
**Current behavior:**
Dropbox shows a long list

**Expected behavior:**
Dropbox should only show three items:
1. Concentration (molar)
2. Concentration (mass)
3. Fraction

**Comment by PavelBal** [comment]
It currently only shows 5 dimensions for me.

In fact, I think we agreed on allowing ANY dimension to be imported? So the bug is the opposite.

**Comment by PavelBal** [comment]
@msevestre @Yuri05 
Current behavior in MoBi: Show all dimensions
Current behavior in PK-Sim: Show only "Fraction", "Dimensionsless", "Amount", "Concentration (mass)", "Concentration (molar)", "Mass"

We should definitely allow all dimensions in MoBi. Why do we want to restrict it in PK-Sim? I would propose to unify and also allow all dimensions in PK-Sim. Otherwise a configuration created in MoBi might be incompatible with import in PK-Sim.

**Comment by PavelBal** [comment]
Discussion from 12.01.: Show all dimensions also in PK-Sim, unify the behavior between PK-Sim and MoBi.

**Comment by PavelBal** [comment]
Importer in PK-Sim still does not show all dimensions:

![image](https://user-images.githubusercontent.com/25903040/154669247-4832a562-6f90-42cb-9aba-0d7b9b8743be.png)

**Comment by PavelBal** [comment]
ignore me please :D
