### ISSUE TITLE
Importer: Confusing behavior when loading the configuration valid for the selected but not for the first sheet

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1459]
An excel file with two sheets - `Sheet A` and `Sheet B` with different structures. A configuration stored as xlm that is valid for `Sheet B`.

- Add observed data -> Select the file.
- Select `Sheet B`
- Load configuration ->Error 
 

```
PK-Sim®

The following excel columns do not exist in the current file. 
 
'Dose [unit]
Concentration (mass) [ng/ml]' 

The corresponding mappings from the configuration will be lost. Do you want to continue?

```

I actually first have to select "Reset configuration based on selected sheet" and then load the configuration... This is not the expected behavior. I think the "Reset configuration based on selected sheet" should be performed in background when loading a configuration.

**Comment by abdelr** [comment]
This could be a nice to have feature but we should think on the different scenarios that could arise. You are presenting the perfect situation where the format will match one of the sheets (not the first though). In contrast, there could be a situation where you have a file with all sheets with the same format and a given format is almost valid for all of them. Let us say all mappings are correct but there is one grouping by parameter in the format that does not exist in the file. Currently, the importer will inform the user, "there is a missing column, are you sure you want to proceed" and if you click yes, it will just ignore the column. Now with the new behavior, it will try to find the sheet that will match the format and since there will not be any we should decide whether to accept the best match (which we need to discuss) or inform that the format is not valid. We need to clearly define all these cases.
