### ISSUE TITLE
Data importer: Unit for "Fraction" is not recognized

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1886]
The default unit for the dimension "Fraction" is an empty string, which is not recognized by the importer.

![image](https://user-images.githubusercontent.com/25903040/216628936-5bd453cc-d381-4d80-a8f7-6767eb18249a.png)
[core-importer-fraction-unit.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/10579777/core-importer-fraction-unit.zip)

**Comment by georgeDaskalakis** [comment]
This was aparently newly introduced by fixing a previous bug a few weeks ago

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/pull/1838

**Comment by georgeDaskalakis** [comment]
Concerning this error in relation to #1837, the behaviour I would suggest altogether is:

A totally empty unit column is allowed and in that case the unit is empty and the dimension "Dimensionless" (this is the first one that the importer finds, if the user explicitely needs to have fraction, she will have to input it manually).

With such a behaviout the file from #1837 still throws an exception, since the measurement unit doesn not match the error unit (error unit column empty) for the specific sheet of the file.

**Comment by PavelBal** [comment]
> A totally empty unit column is allowed and in that case the unit is empty and the dimension "Dimensionless" (this is the first one that the importer finds, if the user explicitely needs to have fraction, she will have to input it manually).

Yes
