### ISSUE TITLE
Code will lead to crash 100%

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1951]
![image](https://user-images.githubusercontent.com/1041237/229366389-9aee0071-aee0-4726-815d-0ff16db587e5.png)

in ModalmporterPresenter
What is this on line 109?

**Comment by georgeDaskalakis** [comment]
@msevestre this has never caused a problem till now because it is there for the case of loading from configuration AND also prompting the user. That could be the case if we wanted to have this as a possibility in reloading observed data.

This was a use case that was in the end not supported and I am not sure it makes sense at all to have a possibility for that anyways. If not I could remove the "PromptForConfirmation" property from dataImporterSettings alltogether.

For sure I am creating a PR that would not make the code crash even in case it would be used.
