### ISSUE TITLE
It is possible to create formulas with the same name as existing

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#2058]
![image](https://user-images.githubusercontent.com/25903040/220959125-4026b571-07c0-4cc8-a9cd-692327b3146d.png)

Yes, the OK Button can be selected :D 

![image](https://user-images.githubusercontent.com/25903040/220959263-7b20b6a2-5deb-495a-b624-b294340ea74a.png)

**Comment by rwmcintosh** [comment]
@PavelBal @Yuri05 @msevestre 

There's some inconsistency in handling naming and renaming objects in MoBi. One of the root causes is this very simple dialog, used when creating an initial name for a new object, is not using case-insensitive comparison to the forbidden values.

![image](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/assets/261477/1d0937b0-3082-4bfe-86ab-b0050ea57b54)

This should only be doing a case-insensitive comparison to the forbidden values when used for naming. The only other application that is used for creating tags. Should that also be a case-insensitive comparison?

The bug here about the ok button still being enabled when invalid is separate but related.

**Comment by PavelBal** [comment]
I think the comparison should always be case-insensitive.
