### ISSUE TITLE
Formulas are resolved before applying PV - unwanted behavior

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#2297]
[formula-resolved-before-pb.zip](https://github.com/user-attachments/files/16523552/formula-resolved-before-pb.zip)

In the attached project, the module `Test2` defines a parameter `Organism|Param` by an invalid formula (the referenced parameter `foo` is not present).

![image](https://github.com/user-attachments/assets/509b3673-976f-4a22-86b3-d9d01a8b52b8)

Additionally, the value of the parameter is defined in the PV BB

![image](https://github.com/user-attachments/assets/f7defc5f-b776-4ee9-b753-8444a23d971f)

When trying to create a simulation, an error is thrown that `foo` is not found. This behavior is unwanted, as I want the value defined in the PV BB to be applied without the formula being evaluated. This is how it worked in MoBi 11, and it was a way to overwrite parameters that otherwise would not be resolved.

**Comment by msevestre** [comment]
@PavelBal I don't think this worked before. PSV were applied after validation . But anyways

**Comment by msevestre** [comment]
ok so this is because of this code here

```
  var actualParameterValue = parameterValue.Value.Value;
  if (parameter.Formula is ConstantFormula constantFormula)
     constantFormula.Value = actualParameterValue;
  else
     parameter.Value = actualParameterValue;
```

We say that if the formula is constant, we overwrite the constant value with the value
Otherwise we simply let the formula and let the isFixedValue= true in the simulation

@Yuri05 and @PavelBal 
I tired to skp validation if the value is overwritten. But this does not work because then we try to resolve references later on
So we need to OVERWRITTE WRONG FORMULAS with constant somehow. That means that we need to evaluate them all again.... doable but a bit of a pain

**Comment by PavelBal** [comment]
> I don't think this worked before. PSV were applied after validation . But anyways

This definitely worked, I relied on this concept a lot in my projects and now I cannot create the simulations because of this changed behavior :)
