### ISSUE TITLE
Observed data format: multiple Ranges

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#648]
Here pretty complex example having multiple ranges in it (s. attachement).
<img width="300" src="https://user-images.githubusercontent.com/25061876/66568074-e30e4480-eb68-11e9-903e-717cb1053430.png">
[ImportTestData2019-09.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/3712487/ImportTestData2019-09.xlsx)

I don't think it should be possible to import everything in only one import process.
Instead, N import processes could be startet; every import process would deliver the data for only one range.

I also don't really see a possibility to update imported observed data from another data source following the workflow in #785

**Comment by msevestre** [comment]
@Yuri05 You don't mean that you want to suport this type of file correct?
Obiously, with range selection, you could import a part of it. But at the end of the day, this format won't scale

**Comment by Yuri05** [comment]
>Obiously, with range selection, you could import a part of it. But at the end of the day, this format won't scale

Yes. Just another example that updating data imported with Range selection is non-trivial
@ulrichSi

**Comment by msevestre** [comment]
I believe we should actively prevent this type of scenario from becoming a standard import. These files should be transformed before import or better should not be created like that in the first place

**Comment by msevestre** [comment]
Still. We should not invest resources and time in trying to import format created because it's easier for a presentation. We will be able to import such file with range selection, but all the automatism such as reimport, update etc... will be very limited/inexistant. 

Hence: From the software point of view, it is fair to not push this type of format to become one of the standard we can import automatically.

**Comment by UlrichSi** [comment]
@msevestre I agree with saving the resources. Importing with range selection will most likely be fine. Updating should at least receive some thoughts on possible implementation, since it often happens that exactly these files are received in several iterations when intermediate results of an ongoing study are evaluated.
