### ISSUE TITLE
Unit test should not open excel files

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#855]
@abdelr @georgeDaskalakis there are some unit tests that are opening excel files. Can we make sure this does not happen?

**Comment by msevestre** [comment]
@georgeDaskalakis Are you getting these notifications?

**Comment by abdelr** [comment]
@msevestre I do receive the notifications. 

This is a topic I wanted to ask about on our meetings but I forgot. We are testing the ExcelDataSourceReader for example. The main responsibility of this class is to read from excel and load into the object for example the sheet names and the data tables. I think we need an excel file for this to be tested. Maybe there is a better option and then we might discuss it and implement it. Could you give us more information here?

**Comment by msevestre** [comment]
I mean open as open excel.
Running all the tests locally leaves instances of Excel open which is not ok

**Comment by abdelr** [comment]
@msevestre @georgeDaskalakis 
OK!! Not good!!
The problem comes from ExportDataTableToExcelTaskSpec.cs file, at class When_exporting_a_dataTable, test should_have_created_data. There is a flag (on true) on the parameter for ExportDataTableToExcel which actually means open the file but I see no way to close it after. I will check with Georgios about this and we'll find a solution.

**Comment by msevestre** [comment]
What about setting that flag to false?;-)

**Comment by georgeDaskalakis** [comment]
yeap that actually worked :) issue fixed
