### ISSUE TITLE
Importer-Redesign: LLOQ column selection disappears

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#869]
If I clear the concentration mapping
![grafik](https://user-images.githubusercontent.com/25061876/104356440-41fcff00-550c-11eb-84fe-a72ba745c9e1.png)
and map the column back again: LLOQ column selection combobox disappears completely
![grafik](https://user-images.githubusercontent.com/25061876/104356550-6062fa80-550c-11eb-8085-c43dce2ad788.png)

@sfrechen @Sulav1 @ju-rgen @Christoph27 FYI

**Comment by abdelr** [comment]
@Yuri05 If you click on "Assign a column" switch currently Off it should turn it On so you can select the column (and not the Default unit anymore). Since you cleared the selection all automatically detected data is cleared including the type of selection (column or default). Please, let me know if it does not work still when clicking on the switch.

**Comment by Yuri05** [comment]
@abdelr no, it's a bug. In the initial set up "Assign a column" applies to the **units only** - and this is as expected. 
So in the situation described above it may not disappear as well.
![grafik](https://user-images.githubusercontent.com/25061876/104435558-d1e28d80-558c-11eb-8b75-32206db585c8.png)
