### ISSUE TITLE
Importer-Redesign: switching SD <=> geoSD

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#870]
<details><summary>Improvement suggestion: replaced by #878</summary>

Currently when switching from arithmetic SD to geometric SD: dimension stays AS IS (e.g. concentration molar)
![grafik](https://user-images.githubusercontent.com/25061876/104357440-7c1ad080-550d-11eb-9890-38e1c16e3e31.png)

It would make more sense to automatically change dimension to "Fraction" in this case.
And when switching from GeoSD to SD: it would make sense to automatically change the dimension to the dimension of the measurement column (e.g. from Fraction to Concentration)

At the moment it's not even possible to select "Fraction"

![grafik](https://user-images.githubusercontent.com/25061876/104358296-8b4e4e00-550e-11eb-9c89-be36e331d3d9.png)

But: when I set dimension (manually) to "Dimensionless", close the settings window and reopen it: dimension is set to Fraction
However: even when set to Fraction: units selection Combobox contains units for Concdentration dimension

![grafik](https://user-images.githubusercontent.com/25061876/104358592-f39d2f80-550e-11eb-8802-183bb992f5e6.png)
</details>

@sfrechen @Sulav1 @ju-rgen @Christoph27 FYI

**Comment by abdelr** [comment]
@Yuri05 This looks like a bug. DimensionFactory.DimensionForUnit retrieves Fraction dimension when invoked with "" as the name of the Unit. The problem is that Dimensionless dimension has a single Unit with the empty string as a name (but it is not retrieved by the factory class). Fraction should not even be listed when changing to Dimensionless since it is not in the list of accepted dimensions under PKSim settings. We should maybe discuss further on this.
